version: "3.9"

services:
  app:
    build: .
    container_name: veeam-notify
    restart: unless-stopped
    environment:
      FLASK_APP: app
      SECRET_KEY: ${SECRET_KEY:-sdfsdfsfsfojgpioje}
      DATABASE_URL: ${DATABASE_URL:-sqlite:////data/app.db}
      TZ: Europe/Paris
    ports:
      - "5005:5000"
    volumes:
      - app_data:/data

volumes:
  app_data:
